### ISSUE TITLE
miracl_reg_mri-allen.sh regmrallen() -- 2 issues

### ISSUE THREAD

**Issue by celstark** [mgoubran/MIRACL#27]
Thanks for putting this project together.  It looks to be **very** helpful for us here.  I've got a few issues that I've hit though.  FWIW, I've grabbed things and built up as Singularity (used to that on my cluster here) but have also checked via Docker and have the same issues:

The first is that function regmrallen(), line 597 calls:
    `c3d ${initallen} -type int -o ${initallen}`
Yet, _initallen_ seems undefined here, so we get an error

> Exception caught of type 16ConvertException
>  When processing command: -o
>  Exception detail: No data has been generated! Can't write to (null)
Looks perhaps like some vestigial code...

The second is that we're calling ants_miracl_mr with a file that doesn't exist:
`ants_miracl_mr -d 3 -f /data/derivatives/miracl/sub-180727/mr_allen_reg/mr.nii.gz -m /code/atlases/ara/template/average_template_50um_OBmasked.nii.gz -o /data/derivatives/miracl/sub-180727/mr_allen_reg/allen_mr_ants -t b -p d -n 32 -s 26 -r 8`
>Moving image '/code/atlases/ara/template/average_template_50um_OBmasked.nii.gz' does not exist. 

Here, _localallen_ was set to /code/atlases/ara/template/average_template_50um_OBmasked.nii.gz

This is happening on line 740:
`allenref=${atlasdir}/ara/template/average_template_50um_OBmasked.nii.gz`

If we have a look in that folder, we see only the 25um versions of all files and a single 50um file:

> ls /code/atlases/ara/template/
> average_template_25um.nii.gz 
> average_template_25um_brainmask.nii.gz
> average_template_25um_OBmasked.nii.gz
> average_template_25um_left.nii.gz
> average_template_25um_OBmasked_left.nii.gz 
> average_template_25um_right.nii.gz
> average_template_25um_OBmasked_right.nii.gz  
> average_template_50um.nii.gz

I've shifted that to use the 25, but don't know if you really intended the 50...

Craig

**Comment by mgoubran** [comment]
Hi @celstark sorry for the late response and thanks for mentioning these issues.. we've been working on updating the docker & singularity containers and got a bit delayed. But we've recently fixed these c3d/ants dependencies issues. We also added the missing masked file to the atlas folder. We tested the docker and singularity containers on our end and on supercomputing clusters. please let us you run into any more issues.
