### ISSUE TITLE
data url not working

### ISSUE THREAD

**Issue by chrisroat** [mgoubran/MIRACL#51]
The following link on the data page seems to no longer exist:

https://stanfordmedicine.app.box.com/s/6kx5tfgbqd6ruk7uo0u64agn4oqpg39i

Is there another place to download data?

**Comment by vsoch** [comment]
I can’t answer your question, but at least when I left about a year ago Stanford was discontinuing box, so it’s not surprising if that link 404s. The maintainer(s) of the repo can hopefully better answer your question!

**Comment by entiri** [comment]
@chrisroat the data link can be found here:

https://www.dropbox.com/sh/i9swdedx7bsz1s8/AABpDmmN1uqPz6qpBLYLtt8va

The link onf the data page will be updated with the upcoming merge
